"""Generate .reg files for ZilKit context menu integration.

This module generates Windows registry files (.reg) that can be imported
to set up the context menu. This approach is more reliable than direct
registry manipulation.
"""

import sys
from pathlib import Path
from typing import Optional

from zilkit.config import get_config
from zilkit.utils.logger import get_logger

logger = get_logger(__name__)


def get_python_exe() -> str:
    """Get the path to the Python executable."""
    return sys.executable


def get_main_script_path() -> Path:
    """Get the path to the main.py script."""
    zilkit_dir = Path(__file__).parent
    return zilkit_dir / "main.py"


def escape_reg_path(path: str) -> str:
    """Escape a path for use in .reg files (double backslashes)."""
    return path.replace("\\", "\\\\")


def generate_reg_files(
    output_dir: Optional[Path] = None,
    python_exe: Optional[str] = None,
    script_path: Optional[Path] = None,
) -> tuple[Path, Path, Path]:
    """Generate .reg files for ZilKit context menu.
    
    Creates three .reg files that should be imported in order:
    1. 1_zilkit_root.reg - Creates the ZilKit root menu
    2. 2_zilkit_submenus.reg - Adds FFmpeg, Utilities, Shortcuts submenus
    3. 3_zilkit_remove.reg - For uninstalling (removes all entries)
    
    Args:
        output_dir: Directory to write .reg files (default: script directory)
        python_exe: Path to Python executable
        script_path: Path to main.py script
    
    Returns:
        Tuple of (install_reg_path, submenus_reg_path, uninstall_reg_path)
    """
    python_exe = python_exe or get_python_exe()
    script_path = script_path or get_main_script_path()
    script_path = script_path.resolve()
    
    if output_dir is None:
        output_dir = Path(__file__).parent.parent / "scripts" / "reg_files"
    
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Escape paths for .reg file format
    python_exe_escaped = escape_reg_path(python_exe)
    script_path_escaped = escape_reg_path(str(script_path))
    
    # Load presets for FFmpeg submenu
    config = get_config()
    presets = config.get_presets()
    preset_list = list(presets.items())
    
    # Generate preset entries
    preset_subcommands = []
    preset_entries = []
    for idx, (preset_key, preset) in enumerate(preset_list, 1):
        preset_cmd_name = f"ZKPreset{idx}"
        preset_subcommands.append(preset_cmd_name)
        display_name = preset.get("display_name", preset_key)
        escaped_preset = preset_key.replace('"', '\\"')
        preset_entries.append(f'''
; Preset {idx}: {display_name}
[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\{preset_cmd_name}]
@="{display_name}"

[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\{preset_cmd_name}\\command]
@="\\"{python_exe_escaped}\\" \\"{script_path_escaped}\\" ffmpeg encode-preset \\"{escaped_preset}\\""
''')
    
    preset_subcommands_str = ";".join(preset_subcommands) if preset_subcommands else ""
    preset_entries_str = "".join(preset_entries)
    
    # =========================================================================
    # File 1: Root menu (creates ZilKit with empty SubCommands first)
    # =========================================================================
    root_reg = f'''Windows Registry Editor Version 5.00
; ZilKit Context Menu - Step 1: Create Root Menu
; Generated by ZilKit

; Create the ZilKit root menu entry
[HKEY_CLASSES_ROOT\\Directory\\Background\\shell\\ZilKit]
"MUIVerb"="ZilKit"
"Icon"="\\"{python_exe_escaped}\\",0"
"SubCommands"=""

'''
    
    # =========================================================================
    # File 2: Submenus and commands
    # =========================================================================
    submenus_reg = f'''Windows Registry Editor Version 5.00
; ZilKit Context Menu - Step 2: Add Submenus and Commands
; Generated by ZilKit

; Update ZilKit root to include all submenus
[HKEY_CLASSES_ROOT\\Directory\\Background\\shell\\ZilKit]
"SubCommands"="ZKFFmpeg;ZKUtilities;ZKShortcuts"

; =============================================================================
; FFMPEG SUBMENU
; =============================================================================
[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKFFmpeg]
"MUIVerb"="FFmpeg"
"SubCommands"="ZKFFmpeg1;ZKFFmpeg2;ZKFFmpeg3;ZKFFmpeg4;ZKFFmpeg5"

; FFmpeg Action 1: Encode To Movie (Default)
[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKFFmpeg1]
@="Encode To Movie (Default)"

[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKFFmpeg1\\command]
@="\\"{python_exe_escaped}\\" \\"{script_path_escaped}\\" ffmpeg encode-default"

; FFmpeg Action 2: Encode To Movie (Choose Preset) - Submenu
[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKFFmpeg2]
"MUIVerb"="Encode To Movie (Choose Preset)"
"SubCommands"="{preset_subcommands_str}"

{preset_entries_str}

; FFmpeg Action 3: Encode To Movie (Multi-Output)
[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKFFmpeg3]
@="Encode To Movie (Multi-Output)"

[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKFFmpeg3\\command]
@="\\"{python_exe_escaped}\\" \\"{script_path_escaped}\\" ffmpeg encode-multi-output"

; FFmpeg Action 4: Encode To Movie (Recursive)
[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKFFmpeg4]
@="Encode To Movie (Recursive)"

[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKFFmpeg4\\command]
@="\\"{python_exe_escaped}\\" \\"{script_path_escaped}\\" ffmpeg encode-recursive"

; FFmpeg Action 5: Configure Default Settings
[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKFFmpeg5]
@="Configure Default Settings"

[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKFFmpeg5\\command]
@="\\"{python_exe_escaped}\\" \\"{script_path_escaped}\\" ffmpeg configure"

; =============================================================================
; UTILITIES SUBMENU
; =============================================================================
[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKUtilities]
"MUIVerb"="Utilities"
"SubCommands"="ZKUtil1"

; Utilities Action 1: Remove Frame Padding
[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKUtil1]
@="Remove Frame Padding"

[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKUtil1\\command]
@="\\"{python_exe_escaped}\\" \\"{script_path_escaped}\\" utilities remove-frame-padding"

; =============================================================================
; SHORTCUTS SUBMENU
; =============================================================================
[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKShortcuts]
"MUIVerb"="Shortcuts"
"SubCommands"="ZKShort1;ZKShort2;ZKShort3"

; Shortcuts Action 1: Empty Recycle Bin
[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKShort1]
@="Empty Recycle Bin"

[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKShort1\\command]
@="\\"{python_exe_escaped}\\" \\"{script_path_escaped}\\" shortcuts empty-recycle-bin"

; Shortcuts Action 2: Force Restart
[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKShort2]
@="Force Restart"

[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKShort2\\command]
@="\\"{python_exe_escaped}\\" \\"{script_path_escaped}\\" shortcuts restart"

; Shortcuts Action 3: Force Shutdown
[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKShort3]
@="Force Shutdown"

[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKShort3\\command]
@="\\"{python_exe_escaped}\\" \\"{script_path_escaped}\\" shortcuts shutdown"

'''

    # =========================================================================
    # File 3: Uninstall (remove all entries)
    # =========================================================================
    # Build list of preset keys to remove
    preset_remove_entries = "\n".join([
        f'[-HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKPreset{i}]'
        for i in range(1, 51)
    ])
    
    # Also remove old ZilKit* keys from previous installation attempts
    old_keys_remove = """
; Remove old ZilKit* keys if they exist
[-HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZilKitFFmpeg]
[-HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZilKitFFmpeg1]
[-HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZilKitFFmpeg2]
[-HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZilKitFFmpeg3]
[-HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZilKitFFmpeg4]
[-HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZilKitFFmpeg5]
[-HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZilKitUtilities]
[-HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZilKitUtilities1]
[-HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZilKitShortcuts]
[-HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZilKitShortcuts1]
[-HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZilKitShortcuts2]
[-HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZilKitShortcuts3]
"""
    
    uninstall_reg = f'''Windows Registry Editor Version 5.00
; ZilKit Context Menu - Uninstall (Remove All Entries)
; Generated by ZilKit

; Remove main menu
[-HKEY_CLASSES_ROOT\\Directory\\Background\\shell\\ZilKit]

; Remove FFmpeg submenu and actions
[-HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKFFmpeg]
[-HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKFFmpeg1]
[-HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKFFmpeg2]
[-HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKFFmpeg3]
[-HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKFFmpeg4]
[-HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKFFmpeg5]

; Remove preset keys
{preset_remove_entries}

; Remove Utilities submenu and actions
[-HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKUtilities]
[-HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKUtil1]

; Remove Shortcuts submenu and actions
[-HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKShortcuts]
[-HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKShort1]
[-HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKShort2]
[-HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CommandStore\\shell\\ZKShort3]

{old_keys_remove}
'''

    # Write files
    root_path = output_dir / "1_zilkit_root.reg"
    submenus_path = output_dir / "2_zilkit_submenus.reg"
    uninstall_path = output_dir / "3_zilkit_remove.reg"
    
    root_path.write_text(root_reg, encoding="utf-16")
    submenus_path.write_text(submenus_reg, encoding="utf-16")
    uninstall_path.write_text(uninstall_reg, encoding="utf-16")
    
    logger.info(f"Generated .reg files in {output_dir}")
    
    return root_path, submenus_path, uninstall_path


def import_reg_file(reg_path: Path) -> bool:
    """Import a .reg file using reg.exe.
    
    Args:
        reg_path: Path to the .reg file
    
    Returns:
        True if successful, False otherwise
    """
    import subprocess
    
    try:
        result = subprocess.run(
            ["reg", "import", str(reg_path)],
            capture_output=True,
            text=True,
            check=True
        )
        logger.info(f"Successfully imported {reg_path.name}")
        return True
    except subprocess.CalledProcessError as e:
        logger.error(f"Failed to import {reg_path.name}: {e.stderr}")
        return False
    except Exception as e:
        logger.error(f"Error importing {reg_path.name}: {e}")
        return False


def register_context_menu_via_reg() -> bool:
    """Register ZilKit context menu by generating and importing .reg files.
    
    Returns:
        True if successful, False otherwise
    """
    try:
        root_path, submenus_path, _ = generate_reg_files()
        
        logger.info("Importing registry files...")
        
        # Import in order (important!)
        if not import_reg_file(root_path):
            return False
        
        if not import_reg_file(submenus_path):
            return False
        
        logger.info("Successfully registered ZilKit context menu")
        return True
        
    except Exception as e:
        logger.exception(f"Error registering context menu: {e}")
        return False


def unregister_context_menu_via_reg() -> bool:
    """Unregister ZilKit context menu by importing the uninstall .reg file.
    
    Returns:
        True if successful, False otherwise
    """
    try:
        _, _, uninstall_path = generate_reg_files()
        
        logger.info("Removing registry entries...")
        
        if not import_reg_file(uninstall_path):
            return False
        
        logger.info("Successfully removed ZilKit context menu")
        return True
        
    except Exception as e:
        logger.exception(f"Error unregistering context menu: {e}")
        return False
